{
  "name": "try-to-catch",
  "description": "function try-catch wrapper for promises",
  "keywords": [
    "try",
    "catch",
    "function",
    "promise",
    "async",
    "await",
    "try-catch",
    "then"
  ],
  "license": "mit",
  "homepage": "http://github.com/coderaiser/try-to-catch",
  "repository": {
    "type": "git",
    "url": "git://github.com/coderaiser/try-to-catch.git"
  },
  "version": "3.0.1",
  "dependencies": {},
  "devDependencies": {
    "coveralls": "^3.0.0",
    "eslint": "^8.10.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-putout": "^14.4.0",
    "madrun": "^9.0.0",
    "nodemon": "^2.0.2",
    "nyc": "^15.0.0",
    "putout": "^25.4.1",
    "supertape": "^7.2.0"
  },
  "users": [],
  "readme": "",
  "peerDependencies": {},
  "developers": [
    "mnemonic.enemy@gmail.com"
  ],
  "kwds": "function try-catch wrapper for promises try catch function promise async await try-catch then",
  "license_kwds": "mit",
  "libtype": "npm",
  "id": "npm_try_to_catch",
  "dependency_ids": [
    "npm_coveralls",
    "npm_eslint",
    "npm_eslint_plugin_node",
    "npm_eslint_plugin_putout",
    "npm_madrun",
    "npm_nodemon",
    "npm_nyc",
    "npm_putout",
    "npm_supertape"
  ]
}