{
  "classifiers": [
    "license :: osi approved :: bsd license",
    "programming language :: python :: 3",
    "programming language :: python :: 3.6",
    "programming language :: python :: 3.7",
    "programming language :: python :: 3.8"
  ],
  "description": "# django-utils-six\n\nforward compatibility django.utils.six for django 3\n\n```bash\npip install django>3\npip install django-utils-six\n```\n\ncode is taken from [django 2.2](https://github.com/django/django/blob/stable/2.2.x/django/utils/six.py)\n\n## why?\n\ni found `django.utils.six` is solely responsible for plenty of libraries' incompatibility with django 3.",
  "docs_url": null,
  "keywords": "django,compatibility,six",
  "license": "bsd-3-clause",
  "name": "django-utils-six",
  "package_url": "https://pypi.org/project/django-utils-six/",
  "project_url": "https://pypi.org/project/django-utils-six/",
  "project_urls": {
    "Homepage": "https://github.com/whtsky/django-utils-six",
    "Repository": "https://github.com/whtsky/django-utils-six"
  },
  "release_url": "https://pypi.org/project/django-utils-six/2.0/",
  "requires_dist": [],
  "requires_python": ">=3.6,<4.0",
  "summary": "forward compatibility django.utils.six for django 3",
  "version": "2.0",
  "releases": [],
  "developers": [
    "django_software_foundation",
    "foundation@djangoproject.com"
  ],
  "kwds": "django pip incompatibility compatibility py",
  "license_kwds": "bsd-3-clause",
  "libtype": "pypi",
  "id": "pypi_django_utils_six",
  "homepage": "https://github.com/whtsky/django-utils-six",
  "release_count": 1,
  "dependency_ids": []
}