{
  "libtype": "pypi",
  "libname": "geographiclib",
  "url": "https://geographiclib.sourceforge.io/python/2.0",
  "html": "<html><head><title>Encountered a 404 error</title><body><p>An error has been encountered in accessing this page.<p>1. <b>Server:</b> geographiclib.sourceforge.io<br />2. <b>URL path:</b> /python/2.0<br />3. <b>Error notes:</b> NONE<br />4. <b>Error type:</b> 404<br />5. <b>Request method:</b> GET<br />6. <b>Request query string:</b> NONE<br />7. <b>Time:</b> 2024-03-05 20:08:17 UTC (1709669297)<p><b>Reporting this problem:</b> The problem you have encountered is with a project web site hosted by SourceForge.net.  This issue should be reported to the SourceForge.net-hosted project (not to SourceForge.net).<p><i>If this is a severe or recurring/persistent problem,</i> please do one of the following, and provide the error text (numbered 1 through 7, above):<ol><li>Contact the project via their <a href=\"https://sourceforge.net/support/prweb-lookup.php?host=geographiclib.sourceforge.io&support=1\">designated support resources</a>.<li>Contact the project administrators of this project via email (see the upper right-hand corner of the <a href=\"https://sourceforge.net/support/prweb-lookup.php?host=geographiclib.sourceforge.io\">Project Summary page</a> for their usernames) at <i>user-name</i>@users.sourceforge.net</ol><p>If you are a maintainer of this web content, please refer to the <a href=\"https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/\">Site Documentation regarding web services</a> for further assistance.<p>NOTE: As of 2008-10-23 directory index display has been disabled by default. This option may be re-enabled by the project by placing a file with the name \".htaccess\" with this line:<p><pre>Options +Indexes</pre></body></html>",
  "embeddings": []
}